package game.actions;

import edu.monash.fit2099.engine.actions.Action;
import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.positions.GameMap;
import game.enemies.Enemies;
import game.interfaces.DropRune;
import game.utils.RunesManager;

/**
 * An Action for enemies to drop runes.
 * Created by:
 * @author Jeremy To Jun Wei
 * Modified by:
 *
 */
public class DropRunesAction extends Action {
    /**
     * actor that is dropping the runes
     */
    private DropRune target;

    /**
     * Constructor
     *
     * @param target enemy that is dropping the runes
     */
    public DropRunesAction(DropRune target){
        this.target = target;

    }

    /**
     * When executed, it will use RuneManager to gain access to player's rune and
     * add random runes amount generated by enemies method
     *
     * @param actor The actor performing the action.
     * @param map The map the actor is on.
     * @return result of enemy dropping rune
     */
    @Override
    public String execute(Actor actor, GameMap map) {
        RunesManager runesManager =  RunesManager.getInstance();
        int randomRunes = target.getRandomRunes();
        runesManager.addRunes(randomRunes);
        return target + " drops " + randomRunes + " runes.";
    }

    /**
     * Describe the drop rune action
     *
     * @param actor The actor performing the action.
     * @return a description used for the menu UI
     */
    @Override
    public String menuDescription(Actor actor) {
        return actor + " drop runes";
    }
}
